### ISSUE TITLE
Running the tool either without stackusage or in sh

### ISSUE THREAD

**Issue by ilya1725** [d99kris/stackusage#5]
Hi:

This may not be a full issue per se.
I really wanted to use your tool on my embedded platform. However, the start script `stackusage` requires `bash`, which I don't have.
I've tried running it using the command line directly:

`SU_FILE=/tmp/stack.txt SU_SIGNO= LD_PRELOAD=/data/Ilya/libstackusage.so DYLD_INSERT_LIBRARIES=/data/Ilya/libstackusage.so DYLD_FORCE_FLAT_NAMESPACE=1 /usr/bin/actuators_proxy`

But it didn't produce any output.
My system runs Busybox shell on `Linux intel-corei7-64 4.8.25-rt10-yocto-preempt-rt `.

**Comment by d99kris** [comment]
Hi @ilya1725 - the command you are using looks fine to me (but you actually only need to set `LD_PRELOAD` and `SU_FILE` for Linux, the DYLD parameters are for macOS/Darwin). I just tried this on my Linux system:
```
LD_PRELOAD="./build/libstackusage.so" SU_FILE="su.log" ./build/ex001
```
and the file `su.log` is created with the output from stackusage.

You mentioned it's an embedded platform, do you have glibc or other libc? I believe stackusage relies on some GNU extensions under Linux.

Other things to possibly check is whether your user can write to `/tmp` and that the compiled library is readable and indeed a library built for the actual platform `file libstackusage.so`. And I assume your program `/usr/bin/actuators_proxy` runs fine when executed by itself? Stackusage (currently) only creates the output file during process shutdown (it registers a `__attribute__ ((destructor))` function that does the logging), so if your program crashes, then this routine is likely not executed.

Unfortunately I don't have any embedded-like busybox-based system to test on here.

**Comment by ilya1725** [comment]
- This is the output from `file libstackusage.so` : `libstackusage.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=02024fd514a07843eec74f53dd963c2890aa362d, not stripped`. 

- I can write to `/tmp/`.

- The program `/usr/bin/actuators_proxy` runs fine by itself. In fact, it runs fine with the aforementioned command. Just no data is collected.

- I do have `/lib/libc.so.6`. 

- I presume the stackusage doesn't have to wait for the program to exit properly to collect the data. Is it correct?

- So I've tried running a different application with the command line you listed and it ran fine, collected the data. Running `actuators_proxy` didn't produce anything. It is a multithreaded program.

**Comment by d99kris** [comment]
> I presume the stackusage doesn't have to wait for the program to exit properly to collect the data. Is it correct?
Actually, by default stackusage only writes its output at program exit. However it is possible to use the `SU_SIGNO` option to have it listen to specified signal and write log output when receiving it.

Example using SIGUSR1:
```
LD_PRELOAD="./build/libstackusage.so" SU_FILE="su.log" SU_SIGNO=`kill -l SIGUSR1` ./build/ex001
kill -s SIGUSR1 `pidof ex001`
```

Please let me know if this works.

**Comment by ilya1725** [comment]
It is working now, thank you.

**Comment by ilya1725** [comment]
Sorry, just a bit of a verification.
I've ran `stackusage` on my application and it returned this:

> stackusage log at 2019-06-17 17:48:00 ----------------------------------------
  pid  id    tid  requested     actual     maxuse  max%    dur  funcP
14645   0  14645    8388608    8388608       2543     0      0  (nil)
14645   1  14646    8388608    8392704       9087     0      0  0x35134d0593
14645   2  14647    8388608    8392704       9087     0      0  0x35134d0593
14645   3  14650    8388608    8392704       9087     0      0  0x35134d0593
14645   4  14651    8388608    8392704       9087     0      0  0x35134d0593
14645   5  14654    8388608    8392704       9087     0      0  0x3512cb9b90
14645   6  14655    8388608    8392704       9087     0      0  0x3512cb9b90
14645   7  14656    8388608    8392704       9087     0      0  0x3512cb9b90
14645   8  14657    8388608    8392704       9087     0      0  0x3512cb9b90
14645   9  14658    8388608    8392704       9087     0      0  0x3512cb9b90
14645  10  14659    8388608    8392704       9087     0      0  0x3512cb9b90
14645  11  14653    8388608    8392704       9087     0      0  0x35134d0593

The amount of stack used for the non-main threads seem a bit too consistent.
However, I've also ran valgrind massif tool and it returned `mem_stacks_B=13320`.
Did you have experience with verifying the returned values and perhaps comparing the output of `stackusage` with other tools?

**Comment by d99kris** [comment]
Hi @ilya1725 - so initially when writing `stackusage` I did check so that the tool was in the same ballpark as valgrind/massif for simple test cases, but it was never an exact match. For the same simple test cases (under `tests/` folder in this project) it is also fairly easy to reason about what the approximate stack usage should be, and whether the tool outputs a reasonable value. And I think it does.

Having that said, `stackusage` has some limitations. The major one being - it only detects stack usage when stack has been written to. Let's say we have a function with only a local variable declaration `char a[1024];` which is never written to, then `stackusage` will not detect that as used stack memory. The reason is that `stackusage` works by filling new stacks with a dummy data pattern, and at termination of the thread it checks how much of that dummy data was left untouched. 

Also, there's some rounding error in `stackusage` of about 512 bytes, which it uses as margin when writing dummy data. So potentially it may report 512 bytes more used than actually used.

I would expect valgrind/massif to give a more correct value, although I haven't checked how it actually measures stack usage.
